"""add Department

Revision ID: 918391570f37
Revises: 98bc9a75748d
Create Date: 2024-04-03 21:04:42.149383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918391570f37'
down_revision = '98bc9a75748d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
